cultureamp/cultureamp-style-guide

.travis.yml

The github token used is from Jason's account, and is set as a secure
variable in the travis-ci.org dashboard

Add initial travis.yml file

---

CHANGELOG.md
package.json
styles/type.scss

This PR is about fixing an error that I found when importing: `debug-vertical-rhythm-grid` mixin.
The error appears to be that we are missing `layers.scss` file from `type.scss`. So this PR is just to add the missing dependency

Import layers.scss from type.scss

---

CHANGELOG.md
guide/src/pages/styles/_TypographyShowcase.js
guide/src/pages/styles/_TypographyShowcase.module.scss
package.json
styles/type.scss

- Fix h3 to be 22px, (before was incorrectly 21px)
- Fix labels to have letter-spacing of 0.5px (but in em, not px)
- Remove "pre" types until we properly define them
- Release 10.2.0 for NPM

Type touchups, hide "pre" types, 10.2.0 release

---

CHANGELOG.md
components/NavigationBar/components/Badge.module.scss
guide/src/components/Demo.module.scss
guide/src/components/HtmlContent.module.scss
guide/src/html.js
guide/src/pages/styles/_TypographyShowcase.js
package.json
styles/type.scss

And don't use sample text on the typography page until we have a nicer design. Using the title for now is much easier to read.

Use new font bundle, lighter heading weights

---

components/Dropdown/Dropdown.js

Currently the label prop in the Dropdown component is a Maybe type, which means if we do not want to display a label, the prop still needs to be passed to avoid a Flow error. This PR seeks to make this prop optional to avoid an unnecessary prop-pass.

Dropdown component:: Make label prop optional

---

CHANGELOG.md
components/Dropdown/Dropdown.js
components/Dropdown/Dropdown.module.scss
components/Layout/Layout.js
components/Layout/Layout.module.scss
components/MenuList/Menu.module.scss
components/MenuList/MenuItem.js
components/NavigationBar/components/Menu.module.scss
components/Text/Text.js
package.json
styles/type.scss

- Add Toasts and Announcers to Layout. Because of the needs of screen-readers to have any `aria-live` regions available on page start-up, I think it justifies these living inside the layout.
- Allow `<Text tag="label">`
- Add automationId props for MenuItem and Dropdown
- Add a chevron to control-action styled dropdowns
- Make control-actions book, not medium
- Fix for underline on MenuItem hover

Front end/layout improvements

---

CHANGELOG.md
package.json
yarn.lock

We have experienced intermittent hangs in the final stages of webpack compilation when two versions of sass-loader are present in the build. By making `sass-loader` a `peerDependency`, we hope to ensure that the consuming project will specify a compatible version range, enabling Yarn/NPM to select a single version of `sass-loader`.

12.2.0: Peer sass-loader

---

CHANGELOG.md
package.json
styles/type.scss

This PR refactors the ideal type mixins so that a different text sizes can be passed through.
Current if you try to pass in a size when including these mixin, you get an error: 
`Parameter $sizeprovided more than once in call to Mixin ca-type-ideal`

Redefine ca-type-ideal mixins

---

.flowconfig
components/Button/Button.js
guide/src/pages/components/Button/_buttonPresets.js
guide/src/pages/components/Icon/_iconPresets.js
guide/src/pages/components/dropdown/_presets.js
guide/src/pages/components/layout/_presets.js
guide/src/pages/components/menulist/_presets.js
guide/src/pages/components/navigationbar/_presets.js
guide/src/pages/components/text/_presets.js
package.json
yarn.lock

Previously it was using `String` rather than `string` and
`Boolean` rather than `boolean` which made it unusable.
We've also updated our style-guide flow config to type check
all the presets in our guide now to catch errors like this in
future.

fix(button): Fix flow type errors in React Button component

---

components/Notification/GlobalNotification.js
components/Notification/InlineNotification.js
components/Notification/ToastNotification.js
components/Notification/__tests__/InlineNotification.test.js
components/Notification/__tests__/__snapshots__/InlineNotification.test.js.snap
components/Notification/_styles.scss
components/Notification/components/GenericNotification.js
components/Notification/components/GenericNotification.module.scss
guide/gatsby-node.js
guide/src/html.js
guide/src/pages/components/notification/_globalPresets.js
guide/src/pages/components/notification/_inlinePresets.js
guide/src/pages/components/notification/_toastPresets.js

- Rename "warning" to "cautionary" in line with Sketch files (breaking change)
- Add "automationId" for all notification types
- Add elm svg icon loader to gatsby config
- Update ideal sans bundle

Front end/react notification fixups

---

components/Icon/Icon.module.scss
guide/src/pages/components/Icon/index.md
guide/src/pages/styles/icons/_InteractionStates.js
guide/src/pages/styles/icons/index.md

Fixes a bug where interactiveIconWrapper still used active/hover states even if disabled.
And adds a new reversedInteractiveIconWrapper class, which is different, and document the differences.

New reverse interaction states

---

components/GlobalIANavigationBar/components/Link.module.scss

translate(calc(...)) doesn't work in IE10 😢 
Have to use two translates instead.
Might even be more performant?
https://stackoverflow.com/a/21469557

Fix IE10 translate + calc issue in navbar

---

components/Icon/Icon.module.scss

`:not(a, b)` syntax is not supported by current browsers, and is not transpiled by our CSS postprocessor (apparently).

Fix broken interactive icon highlight styles

---

guide/src/components/Demo.js
guide/src/components/Demo.module.scss
guide/src/pages/components/Button/button.md
guide/src/pages/components/Button/icon-button.md
guide/src/pages/components/Icon/index.md
guide/src/pages/components/layout/index.md
guide/src/pages/components/menulist/index.md
guide/src/pages/components/navigationbar/index.md
guide/src/pages/components/notification/global.md
guide/src/pages/components/notification/inline.md
guide/src/pages/components/notification/toast.md

* Removed Elm component availability text from markdown. 
* Use 'elm' prop on `Demo` react component to determine if an Elm component is available instead.

Automatic text for Elm component availability

---

package.json
yarn.lock

We had a string of errors with this polyfill when using inline SVGs in our pages (as we do for
icons). The updated version of the library contains a fix for this.

fix(button): Upgrade focus-visible polyfill to fix IE11 errors

---

components/Button/Button.elm

This PR competes with https://github.com/cultureamp/cultureamp-style-guide/compare/mab/button-extra-attributes. Please pick one! (or none)
This requirement came about as we are embedding a small form component inside a legacy backend driven form.
**Pros to this approach over letting users add arbitrary attributes**:
- Dissuades people from using using antipatterns such as `target=_blank`
- The Elm compiler can stop users from giving incorrect attributes/values such as `type=sbmit`
**Cons**
See https://github.com/cultureamp/cultureamp-style-guide/compare/mab/button-extra-attributes.

add ability to add type=submit|reset attribute to Button.elm

---

components/Button/components/GenericButton.js
guide/src/pages/components/Button/_buttonPresets.js

This adds the ability to add a `type` prop to the React Button component, similar to what was done for the Elm Button in #121.
Technically a button's type can be `'submit'`, `'reset'` or `'button'` but for consistency with the Elm API I've kept the React one as `'submit' | 'reset'` as well. If this is a problem let me know.

Add ability to add type=submit|reset to React Button

---

guide/src/pages/language/checklist.md

I noticed http://www.cultureamp.design/language/checklist had unbalanced parentheses around “have the courage to be vulnerable!”.

language checklist: add missing parenthesis

---

components/Button/_styles.scss

This allows for a row of secondary buttons to sit together more compactly.

fix(button): Reduce padding on secondary buttons

---

.travis.yml

Semantic-release is smart enough to know not to deploy if we're not on master.
Now builds will fail if semantic-release fails.

No longer use travis-deploy-once

---

components/Button/_styles.scss

- Increases the padding of secondary buttons
- Fixes an issue where the focus state padding was inconsistent
- Removes label margin for secondary buttons without an icon

Adjust spacing for secondary buttons

---

components/Notification/_styles.scss

In IE10 the default value for flex is `0 0 auto` rather than `0 1 auto` as defined in the latest spec.
Which means this happens:

Fix flex child overflowing in ie10

---

components/Dropdown/Dropdown.js
components/Dropdown/Dropdown.module.scss
guide/src/pages/components/Dropdown/_presets.js

This PR is about adding reversed variant on our `Dropdown` re-usable component so therefore we can use this component to do:

Add reversed variant on our reusable dropdown component

---

components/Notification/Notification.elm
components/Notification/__tests__/__snapshots__/GlobalNotification.test.js.snap
components/Notification/__tests__/__snapshots__/InlineNotification.test.js.snap
components/Notification/__tests__/__snapshots__/ToastNotification.test.js.snap
components/Notification/components/GenericNotification.js
components/Notification/components/__tests__/__snapshots__/GenericNotification.test.js.snap

adds type="button"  on generic notification dismiss button. This prevents submitting forms by accident when dismissing notifications if the notification is inside a form tag

set type=button on generic notification dismiss button

---

components/GlobalIANavigationBar/NavigationBar.js
components/GlobalIANavigationBar/components/Link.js
components/GlobalIANavigationBar/components/Link.module.scss
components/GlobalIANavigationBar/components/Menu.js
components/GlobalIANavigationBar/constants.js
components/OffCanvas/OffCanvas.js
components/OffCanvas/OffCanvas.module.scss
components/OffCanvas/components/Footer.js
components/OffCanvas/components/Header.js
components/OffCanvas/components/Header.module.scss
components/OffCanvas/components/Menu.js
components/OffCanvas/components/Menu.module.scss
components/OffCanvas/index.js
package.json
styles/layout.scss
styles/responsive.scss
yarn.lock

**This adds a few things for responsive navigation:**
- An "OffCanvas" component, both controlled (with trigger) and uncontrolled (BYO trigger), that can house GlobalIANavigationBar Links and Menus.
- A set of responsive media query sass mixins.
- `react-media`, which is a helper component that abstracts over the native `matchMedia` browser API.
**A few things needed to be changed/added to the GlobalIANavigationBar component, but the API (surprisingly) didn't need to be broken in the process:**
- GlobalIANavigationBar.NavigationBar can take a `footerComponent` prop, which renders inside the top level OffCanvas menu.
- GlobalIANavigationBar.Menu can take a `heading` prop, which is what will render in the trigger link as well as the header of the nested OffCanvas menu.

OffCanvas navigation component

---

components/Button/components/GenericButton.js

This PR updates Button types so that it's ok to use async functions in Button `onClick`s.
```
async function sendData() {
// ...
}
function MyComponent() {
return (
<Button
label="Click me"
onClick={sendData} // <- error
/>
);
}
```
Currently Flow errors on the `onClick={sendData}` line when `sendData` is an async function. This is because an async function implicitly returns a Promise which is not compatible with the `void` return type currently defined for a Button's `onClick`.
I changed it to `any` because the Button should not really be concerned with the return type of the function passed to it in `onClick`.
The current workaround is to wrap the async function in a function that doesn't return anything, and pass that to `onClick`.

Allow async functions to be used in Button onClick

---

components/Dropdown/Dropdown.js
components/Dropdown/Dropdown.module.scss
components/Dropdown/__tests__/Dropdown.test.js
components/Dropdown/__tests__/__snapshots__/Dropdown.test.js.snap
guide/src/pages/components/Dropdown/_presets.js

This PR is about adding the reversed property back to this component. I added this property a while back https://github.com/cultureamp/cultureamp-style-guide/pull/167 but I think it got removed accidentally.
To prevent this in the future, I also added a couple of jest tests to ensure that this won't get deleted again :)
I also noticed that the default icon is not being displayed in the dropdown component when the icon and the label are not present. So this PR includes this fix too :)

Add reversed dropdown property back

---

components/GlobalIALayout/_styles.scss

This fixes the content area max-width when there is **no sidebar**. The current value of `900px` appears to be a leftover/oversight because it actually results in less usable space compared to when there is a sidebar.
With sidebar + content.
Total width = 1416
Without sidebar.
Total width = 900
I've checked with the designers who agreed that content area should be `1080px` as defined by `$ca-layout-content-width`.
In Murmur, all uses of `%global-ia-content` have an accompanying sidebar, so this issue hasn't yet shown itself.

fix(GlobalIALayout): Fix content area width when there is no sidebar

---

components/GlobalIANavigationBar/components/Link.js
components/GlobalIANavigationBar/components/Tooltip.js
components/GlobalIANavigationBar/components/Tooltip.module.scss

Make it so the global IA navbar tooltip can be positioned below the element by passing through a
prop

Bottom positioned global nav tooltip

---

components/Notification/_styles.scss

For now, the mobile UI is not optimized for notifications. They will be hidden on smaller screen
sizes in the interem

feat(Notification): Hide notification on small screens

---

components/OffCanvas/OffCanvas.js
components/OffCanvas/OffCanvas.module.scss
components/OffCanvas/components/Menu.module.scss

The off canvas menu exhibited some extra horizontal scrolling on iOS mobile safari.
The change in `components/OffCanvas/components/Menu.module.scss` fixes that.
There is also a refactor of the hamburger so that it's size and color can more easily be adjusted.

Fix off canvas menu overflow

---

guide/src/pages/guides/animation/examples/AnimationImportExample.scss

When using /animations reference webpack fails to find the correct path. /animation points to the
correct scss file.

docs(AnimationImportExample.js): fixed incorrect import reference

---

components/Button/Button.elm
components/Button/_styles.scss
components/Button/components/GenericButton.js
components/Button/components/GenericButton.module.scss
guide/src/pages/components/Button/_buttonPresets.js
guide/src/pages/components/Button/button.md

Before:
During (before design review):
After (squashed line height, icon aligned with first row):

Front end/fix button overflow

---

components/Button/components/GenericButton.js

Currently, if we use a Button component with the `reversed` prop but do not pass in a `reversedColor` prop, the component logs a `console.warn` message. This is just noise for the developer and clutters up Bugsnag with minimal benefit. This PR removes the message clean up the noise while we work towards a more sensible type-checked approach.

fix(button): Remove console.warn for missing reverseColor prop

---

components/Text/Text.elm
components/Text/Text.js
components/Text/Text.module.scss
guide/src/pages/components/Text/_presets.js

New `inline` prop removes margin from text and sets display to `inline-flex`. Useful for aligning headings with other elements e.g. Button

feat(kaizen): add inline prop option to Text component

---

components/Notification/_styles.scss

Title color was affected by global styles. This forces the title to inherit the color of its parent.
https://trello.com/c/fZ8ILhML

fix(Notification): Fix title color

---

components/Button/components/GenericButton.js

Here's a tiny thing. :)
This attribute is useful for buttons with custom behaviour that aren't meant for submitting form data (which is the default behaviour).
It prevents buttons from accidentally submitting a form element they happen to be in, without having to prevent default etc in your code.
MDN has a bit more info:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#attr-type

Allow type="button" attribute for buttons

---

.travis.yml

The builds are failing because the NPM tokens are old, and we don't autopublishing anymore,
so I'm just removing the semantic-release build step.
Dead weight CUT.

Don't run semantic release anymore
