cultureamp/cultureamp-style-guide

CHANGELOG.md, components/NavigationBar/components/Menu.module.scss, package.json
=> Fix Navigation Bar menu styles

.travis.yml, CHANGELOG.md, components/NavigationBar/components/Link.js, package.json, yarn.lock
- Upgrade flow
- Fix an error with the new version
- Get flow to run as part of travis build
Release 10.0.2
=> Fix flow errors

components/Button/Button.js, components/Dropdown/Dropdown.js, components/Dropdown/DropdownMenu.js, components/GlobalIALayout/Layout.js, components/GlobalIANavigationBar/NavigationBar.js, components/GlobalIANavigationBar/components/Badge.js, components/GlobalIANavigationBar/components/Link.js, components/GlobalIANavigationBar/components/Menu.js, components/Icon/Icon.js, components/Layout/Layout.js, components/MenuList/MenuHeader.js, components/MenuList/MenuItem.js, components/MenuList/MenuList.js, components/MenuList/MenuSeparator.js, components/NavigationBar/NavigationBar.js, components/NavigationBar/components/Badge.js, components/NavigationBar/components/Link.js, components/NavigationBar/components/Menu.js, components/NavigationBar/components/Tooltip.js, components/Text/Text.js
… for better JSX documentation
=> fix(react): Add displayNames to all React components

components/Button/Button.elm, components/Button/Button.js, components/Button/Button.module.scss, components/Button/_styles.scss, guide/src/pages/components/Button/Demo.elm, guide/src/pages/components/Button/_buttonPresets.js
`<Button label="Click" secondary>` in React.
`Button.view Button.secondary "Click"` in Elm.
=> feat(Button): Add Secondary Button variant

.flowconfig, components/Button/Button.js, components/Dropdown/Dropdown.js, components/GlobalIANavigationBar/components/Link.js, components/Icon/Icon.js, components/NavigationBar/components/Link.js, util/svg-loader-stub.js
Most of this work was done by @nikuda in #110, I'm splitting it out into a smaller PR.
=> Add flow type checking to Icon component

components/GlobalIANavigationBar/NavigationBar.module.scss, components/GlobalIANavigationBar/components/Link.js, components/GlobalIANavigationBar/components/Link.module.scss
This changes the hover and active states for the GlobalIANavigationBar to look similar to this codepen:
https://codepen.io/diana-macdonald/pen/b76b942d049a4f20b5c56e33c77045d8?editors=0110
=> Update GlobalIANavigationBar link active and hover states

components/Notification/Notification.elm, components/Notification/_styles.scss, components/Notification/components/GenericNotification.js, components/Notification/components/GenericNotification.module.scss, components/Notification/components/__tests__/__snapshots__/GenericNotification.test.js.snap, elm-package.json, guide/elm-package.json, guide/src/components/Demo.js, guide/src/pages/components/Button/Demo.elm, guide/src/pages/components/Button/IconButtonDemo.elm, guide/src/pages/components/Demo.elm, guide/src/pages/components/notification/Demo.elm, guide/src/pages/components/notification/_globalPresets.js, guide/src/pages/components/notification/_inlinePresets.js, guide/src/pages/components/notification/_toastPresets.js, guide/src/pages/components/notification/global.md, guide/src/pages/components/notification/inline.md, guide/src/pages/components/notification/toast.md, webpack/elmSvgAssetLoader.js
Still to do:
- ~I began to add this (and almost had it working), but then realised without the mouse event from clicking cancel, I don't know how tall the notification is so my exiting animation won't animate correctly. I'm going to leave this as an impossible state for now.~ Got it working, view the commit message for details
=> Front end/elm notifications

components/GlobalIALayout/_styles.scss, styles/layout.scss, styles/type.scss
Move global IA layout styles into new layout stylesheet
=> Create layout stylesheet with global styles

icons/arrow-down.svg
This PR is to change the fill colour of arrow down svg icon so that we can colour it
=> Fix arrow down icon

components/Dropdown/Dropdown.module.scss, components/Dropdown/DropdownMenu.js, components/MenuList/Menu.module.scss
=> add rtl styling for dropdown component

components/GlobalIALayout/_styles.scss, styles/layout.scss
…widths for the sidebar and main content areas.
=> Update max width sizing and refine margins and padding

components/GlobalIANavigationBar/NavigationBar.module.scss, components/GlobalIANavigationBar/components/Menu.module.scss, guide/yarn.lock, yarn.lock
Menu was too far to right and being cut off by right side of screen in IE10 and IE11.
This fix moved it back to the correct position. It also brought the arrow down slightly
as it was too high up and there was a slight gap between it and the menu.
=> fix(Global IA menu component): Alignment of global IA dropdown menu

components/NavigationBar/components/Tooltip.module.scss, guide/yarn.lock, styles/layout.scss, yarn.lock
```ca-padding-start() -> ca-padding($start, $end, $top, $bottom)```
```ca-position-start() -> ca-position($start, $end, $top, $bottom)```
```ca-margin-start() -> ca-margin($start, $end, $top, $bottom)```
BREAKING CHANGE: Existing layout mixins will no longer exist and will need to be updated
=> feat(styles): update layout mixins to take all values

guide/package.json, guide/yarn.lock, package.json, yarn.lock
removed motion-ui dep from styleguide as this is a responsibility of the component library
=> fix(styles): add motion-ui as dependency of component library

guide/src/pages/_sitemap.js, guide/src/pages/guides/index.md, guide/src/pages/guides/localisation/examples/CAMarginExample.js, guide/src/pages/guides/localisation/examples/CAPaddingExample.js, guide/src/pages/guides/localisation/examples/CAPositionExample.js, guide/src/pages/guides/localisation/examples/CATypeAlignExample.js, guide/src/pages/guides/localisation/examples/LocalisationMixinImportExample.js, guide/src/pages/guides/localisation/examples/RTLLayoutExample.js, guide/src/pages/guides/localisation/index.md, guide/src/pages/index.md
@sebpearce - please have a look (run locally) and make any changes you think are needed and lets get this out asap.
=> feat(guide): add localisation technical guide

guide/src/pages/guides/localisation/examples/CATypeAlignExample.js, guide/src/pages/guides/localisation/index.md
I noticed a typo in one of the mixin code examples so I went through and proofread the rest just to make it conform to CA language style as much as possible.
=> Proofread and fix typos

components/GlobalIANavigationBar/NavigationBar.module.scss, components/GlobalIANavigationBar/components/Link.js, components/GlobalIANavigationBar/components/Link.module.scss, guide/src/components/Demo.js
Make it so links can be opened in new tab from navbar. Includes tooltip.
=> Global navbar new tab links

components/GlobalIALayout/__tests__/Layout.test.js, components/GlobalIALayout/__tests__/__snapshots__/Layout.test.js.snap
Adds tests for the `GlobalIALayout` component. Makes sure that `displayName` is correctly set for each component and makes sure that each component renders with correct CSS class name and attributes. Also makes sure that when `GlobalIALayout` is used with child components that it slots them in the right positions.
=> Add unit tests for GlobalIALayout

components/GlobalIANavigationBar/NavigationBar.js, components/GlobalIANavigationBar/NavigationBar.module.scss, components/GlobalIANavigationBar/components/Link.module.scss, components/GlobalIANavigationBar/components/Menu.js, components/GlobalIANavigationBar/constants.js, components/OffCanvas/OffCanvas.js, components/OffCanvas/OffCanvas.module.scss, components/OffCanvas/index.js, styles/layout.scss, styles/responsive.scss
Some tweaks for tablet sized screens
=> Responsive updates

components/Notification/_styles.scss
Enabling notifications on mobile again, because we have a responsive fix for the dashboard within Murmur.
=> Show notifications on mobile

components/Button/Button.elm, components/Button/Button.js, components/Button/components/GenericButton.js, components/Button/components/GenericButton.module.scss, guide/src/components/Demo.js, guide/src/components/Demo.module.scss, guide/src/pages/components/Button/ButtonDemo.elm, guide/src/pages/components/Button/_buttonPresets.js
=> feat(button): add fullWidth option to button component

guide/src/pages/language/index.md
See this thread: https://cultureamp.slack.com/archives/C04GLA23U/p1547601184008300
=> docs(language): Titles should be sentence case

components/Button/components/GenericButton.module.scss
=> fix(button): center full width button content
